source 'https://rubygems.org'

gem 'pg'
gem 'rails'
gem 'active_model_serializers', '~> 0.10.0'

# logs
gem 'syslogger'
gem 'lograge'

# files
gem 'paperclip'
gem 'aws-sdk', '~> 2.3.0'

# Newrelic
gem 'newrelic_rpm'

# CORS
gem 'rack-cors', :require => 'rack/cors'

gem 'minitest-rails'
group :test do
  gem 'minitest-focus'
  gem 'faker'
  gem 'database_cleaner'
  gem 'codecov', :require => false
end

group :development do
  gem 'spring'
  gem 'rubocop', require: false
  # documentation
  gem 'yard'
end

group :production do
  gem 'unicorn'
end

group :aws do
  gem 'unicorn'
end
